#!/usr/bin/env python3
"""Generate a strong-override hook TU for the Split/Second engine module.

Input: JSON list or CSV of {va, name, arity, dump_words(optional)}.
  JSON: [{"va": "0x888D9838", "name": "Release", "arity": 4, "dump_words": 8}, ...]
  CSV : va,name,arity[,dump_words]   (lines starting with # ignored)
Output (default tools/d3d/hooks/generated_hooks.cpp): one
  extern "C" void sub_VA(PPCContext& __restrict ctx, uint8_t* base)
per entry that prints
  D3DTRACE f=<frame> lr=<lr> fn=<name> r3=.. r4=.. [d=[w0 w1 ..]]
to stderr, then calls __imp__sub_VA. The present function sub_888EB588 is
always hooked; its override increments the frame counter and emits a
  D3DCOUNT f=<frame> <name>=<calls> ...
line with per-function call counts for the frame that just ended.

Per-call D3DTRACE lines are only printed while verbose tracing is on. Verbose
tracing is armed by a trigger file: when the file named by env D3DTRACE_TRIGGER
exists at present time it is deleted and the next D3DTRACE_FRAMES (default 1)
frames are printed in full (same mechanism as --gpu_draw_trace_trigger_file so
both can be touched together). D3DTRACE_ALWAYS=1 prints every call.

Alignment with the xenos draw trace: the CP runs ~2 swaps behind the CPU's
present calls, so touching both trigger files at once traces different frames.
If D3DTRACE_GPU_TRIGGER (path of --gpu_draw_trace_trigger_file) is set, the
present override creates that file itself D3DTRACE_GPU_LAG (default 2) presents
after the verbose frame started, so the CP traces the swap whose D3D calls were
printed. tracecat.py reports the residual delta (traced_swap - verbose_frame).
"""
import sys, json, csv, argparse, os

PRESENT = 0x888EB588

def load(path):
    if path.endswith('.json'):
        items = json.load(open(path))
    else:
        items = []
        for row in csv.reader(l for l in open(path) if l.strip() and not l.startswith('#')):
            d = {'va': row[0], 'name': row[1], 'arity': row[2] if len(row) > 2 else 4}
            if len(row) > 3 and row[3]: d['dump_words'] = row[3]
            items.append(d)
    out = []
    for d in items:
        va = d['va']; va = int(va, 16) if isinstance(va, str) else int(va)
        out.append({'va': va, 'name': d.get('name') or 'sub_%08X' % va,
                    'arity': int(d.get('arity', 4)), 'dump_words': int(d.get('dump_words', 0) or 0)})
    return out

def gen(items):
    if not any(i['va'] == PRESENT for i in items):
        items = items + [{'va': PRESENT, 'name': 'Present', 'arity': 4, 'dump_words': 0}]
    items = sorted(items, key=lambda i: i['va'])
    L = []
    w = L.append
    w('// Generated by tools/d3d/hookgen.py - do not edit.')
    w('#include <cstdio>')
    w('#include <cstdlib>')
    w('#include <cstdint>')
    w('#include <unistd.h>')
    w('#include "splitsecond_funcs.h"')
    w('')
    w('namespace {')
    w('uint32_t g_frame = 0;')
    w('int g_verbose_frames = 0;      // frames left to print per-call lines')
    w('int g_always = -1;')
    w('const char* g_trigger = nullptr;')
    w('uint32_t g_gpu_trigger_at = 0;')
    w('enum { kNumHooks = %d };' % len(items))
    w('uint32_t g_counts[kNumHooks] = {};')
    w('const char* const g_names[kNumHooks] = {')
    for i in items: w('  "%s",' % i['name'])
    w('};')
    w('inline bool verbose() {')
    w('  if (g_always < 0) { const char* a = getenv("D3DTRACE_ALWAYS"); g_always = (a && *a && *a != \'0\') ? 1 : 0; }')
    w('  return g_always || g_verbose_frames > 0;')
    w('}')
    w('}  // namespace')
    w('')
    for idx, i in enumerate(items):
        va = i['va']; fn = 'sub_%08X' % va
        w('extern "C" void __imp__%s(PPCContext& __restrict, uint8_t*);' % fn)
        w('extern "C" void %s(PPCContext& __restrict ctx, uint8_t* base) {' % fn)
        if va == PRESENT:
            w('  // Frame boundary: report counts for the frame that just ended, then advance.')
            w('  if (g_frame) {')
            w('    fprintf(stderr, "D3DCOUNT f=%u", g_frame);')
            w('    for (int k = 0; k < kNumHooks; ++k) fprintf(stderr, " %s=%u", g_names[k], g_counts[k]);')
            w('    fputc(\'\\n\', stderr);')
            w('  }')
            w('  for (int k = 0; k < kNumHooks; ++k) g_counts[k] = 0;')
            w('  ++g_frame;')
            w('  if (g_verbose_frames > 0) --g_verbose_frames;')
            w('  if (!g_trigger) { const char* t = getenv("D3DTRACE_TRIGGER"); g_trigger = t ? t : ""; }')
            w('  if (*g_trigger && access(g_trigger, F_OK) == 0) {')
            w('    unlink(g_trigger);')
            w('    const char* n = getenv("D3DTRACE_FRAMES"); g_verbose_frames = n ? atoi(n) : 1;')
            w('    fprintf(stderr, "D3DTRACE-TRIGGER f=%u frames=%d\\n", g_frame, g_verbose_frames);')
            w('    const char* gt = getenv("D3DTRACE_GPU_TRIGGER");')
            w('    if (gt && *gt) { const char* lg = getenv("D3DTRACE_GPU_LAG"); g_gpu_trigger_at = g_frame + (lg ? atoi(lg) : 2); }')
            w('  }')
            w('  if (g_gpu_trigger_at && g_frame >= g_gpu_trigger_at) {')
            w('    g_gpu_trigger_at = 0;')
            w('    FILE* tf = fopen(getenv("D3DTRACE_GPU_TRIGGER"), "w"); if (tf) fclose(tf);')
            w('    fprintf(stderr, "D3DTRACE-GPUTRIGGER f=%u\\n", g_frame);')
            w('  }')
        w('  ++g_counts[%d];' % idx)
        w('  if (verbose()) {')
        regs = ' '.join('r%d=%%08x' % (3 + k) for k in range(i['arity']))
        args = ', '.join('ctx.r%d.u32' % (3 + k) for k in range(i['arity']))
        w('    fprintf(stderr, "D3DTRACE f=%%u lr=%%08x fn=%s %s", g_frame, (uint32_t)ctx.lr%s);' % (i['name'], regs, (', ' + args) if args else ''))
        if i['dump_words'] > 0:
            w('    if (ctx.r3.u32 >= 0x10000 && ctx.r3.u32 < 0xC0000000u) {')
            w('      fputs(" d=[", stderr);')
            w('      for (uint32_t k = 0; k < %d; ++k) fprintf(stderr, "%%08x ", (uint32_t)REX_LOAD_U32(ctx.r3.u32 + 4 * k));' % i['dump_words'])
            w('      fputc(\']\', stderr);')
            w('    }')
        w('    fputc(\'\\n\', stderr);')
        w('  }')
        w('  __imp__%s(ctx, base);' % fn)
        w('}')
        w('')
    w('extern "C" void d3dtrace_flush() { fflush(stderr); }')
    return '\n'.join(L) + '\n'

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('input')
    ap.add_argument('-o', '--out', default=os.path.join(os.path.dirname(os.path.abspath(__file__)), 'hooks', 'generated_hooks.cpp'))
    a = ap.parse_args()
    items = load(a.input)
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    open(a.out, 'w').write(gen(items))
    print('%s: %d hooks' % (a.out, len(items) + (0 if any(i['va'] == PRESENT for i in items) else 1)))

if __name__ == '__main__': main()
