#!/usr/bin/env python3
"""Generate a timing hook TU for the engine's D3D band.

Wraps every D3D entry point in a strong `sub_VA` override that measures
wall-clock time spent inside the call, counting only the outermost D3D call on
each thread so nested band calls are not double-counted. The present override
reports, once per frame, how much of that thread's frame was spent inside the
D3D band.

    python3 tools/d3d/timehooks.py [entrypoints.json] [-o out.cpp]
    bash tools/d3d/build_hooks.sh tools/d3d/hooks/timing_hooks.cpp

Output line (stderr, one per present, per thread that presents):

    D3DTIME f=<frame> tid=<tid> wall_ms=<frame wall> d3d_ms=<in band> calls=<n> \
        top: <name>=<ms>/<calls> ...

Environment: D3DTIME_TOP (default 10) top entries per line, D3DTIME_EVERY
(default 1) report every Nth frame.
"""
import argparse
import json
import sys

PRESENT = 0x888EB588

# Entry points already overridden in src/ (the link would see two definitions).
# They keep their table slot, so indices stay comparable, but are not timed.
EXCLUDE = {0x888D3618}

PROLOGUE = '''// Generated by tools/d3d/timehooks.py - do not edit.
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <ctime>
#include <unistd.h>
#include "splitsecond_funcs.h"

namespace {

enum { kNumHooks = %(count)d };

const char* const g_names[kNumHooks] = {
%(names)s};

// Per-thread accumulators: the band is called from several guest threads and
// only the presenting thread's frame is interesting.
struct Acc {
  uint64_t ns[kNumHooks];
  uint32_t calls[kNumHooks];
  uint64_t total_ns;
  uint32_t total_calls;
  uint64_t frame_start_ns;
  int depth;
};
thread_local Acc g_acc = {};
uint32_t g_frame = 0;
int g_top = -1;
int g_every = -1;

inline uint64_t now_ns() {
  timespec t;
  clock_gettime(CLOCK_MONOTONIC, &t);
  return uint64_t(t.tv_sec) * 1000000000ull + uint64_t(t.tv_nsec);
}

inline void enter(uint64_t& t0) { t0 = now_ns(); }

inline void leave(int index, uint64_t t0) {
  uint64_t d = now_ns() - t0;
  g_acc.ns[index] += d;
  g_acc.calls[index]++;
  g_acc.total_ns += d;
  g_acc.total_calls++;
}

void report() {
  if (g_top < 0) {
    const char* top = getenv("D3DTIME_TOP");
    g_top = top ? atoi(top) : 10;
    const char* every = getenv("D3DTIME_EVERY");
    g_every = every ? atoi(every) : 1;
    if (g_every < 1) g_every = 1;
  }
  uint64_t now = now_ns();
  uint64_t wall = g_acc.frame_start_ns ? now - g_acc.frame_start_ns : 0;
  g_acc.frame_start_ns = now;
  uint32_t frame = g_frame++;
  if (wall && (frame %% (uint32_t)g_every) == 0) {
    fprintf(stderr, "D3DTIME f=%%u tid=%%d wall_ms=%%.3f d3d_ms=%%.3f calls=%%u top:",
            frame, (int)gettid(), double(wall) / 1e6,
            double(g_acc.total_ns) / 1e6, g_acc.total_calls);
    for (int n = 0; n < g_top; ++n) {
      int best = -1;
      uint64_t best_ns = 0;
      for (int i = 0; i < kNumHooks; ++i) {
        if (g_acc.ns[i] > best_ns) { best_ns = g_acc.ns[i]; best = i; }
      }
      if (best < 0) break;
      fprintf(stderr, " %%s=%%.3f/%%u", g_names[best], double(best_ns) / 1e6,
              g_acc.calls[best]);
      g_acc.ns[best] = 0;  // consumed; the whole accumulator is cleared below
    }
    fputc('\\n', stderr);
  }
  for (int i = 0; i < kNumHooks; ++i) { g_acc.ns[i] = 0; g_acc.calls[i] = 0; }
  g_acc.total_ns = 0;
  g_acc.total_calls = 0;
}

}  // namespace

'''

HOOK = '''extern "C" void __imp__sub_%(va)08X(PPCContext& __restrict, uint8_t*);
extern "C" void sub_%(va)08X(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_%(va)08X(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_%(va)08X(ctx, base);
  leave(%(index)d, t0);
  --g_acc.depth;
%(extra)s}

'''


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('entrypoints', nargs='?',
                        default='docs/d3d/entrypoints.json')
    parser.add_argument('-o', '--output',
                        default='tools/d3d/hooks/timing_hooks.cpp')
    args = parser.parse_args()

    items = json.load(open(args.entrypoints))
    eps = []
    for item in items:
        va = item['va']
        va = int(va, 16) if isinstance(va, str) else int(va)
        eps.append((va, item.get('name') or 'sub_%08X' % va))
    if not any(va == PRESENT for va, _ in eps):
        eps.append((PRESENT, 'Present'))
    eps.sort()

    names = ''.join('  "%s@%04X",\n' % (name.replace('"', ''), va & 0xFFFF)
                    for va, name in eps)
    out = [PROLOGUE % {'count': len(eps), 'names': names}]
    for index, (va, _name) in enumerate(eps):
        if va in EXCLUDE:
            continue
        out.append(HOOK % {'va': va, 'index': index,
                           'extra': '  report();\n' if va == PRESENT else ''})
    text = ''.join(out)
    with open(args.output, 'w') as handle:
        handle.write(text)
    print('%s: %d hooks (present %s)' % (args.output, len(eps),
                                         '0x%08X' % PRESENT), file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
