// Generated by tools/d3d/hookgen.py - do not edit.
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <unistd.h>
#include "splitsecond_funcs.h"

namespace {
uint32_t g_frame = 0;
int g_verbose_frames = 0;      // frames left to print per-call lines
int g_always = -1;
const char* g_trigger = nullptr;
uint32_t g_gpu_trigger_at = 0;
enum { kNumHooks = 200 };
uint32_t g_counts[kNumHooks] = {};
const char* const g_names[kNumHooks] = {
  "ep_888D19C0",
  "ep_888D1AF8",
  "ep_888D1B10",
  "ep_888D1B28",
  "ep_888D1C48",
  "ep_888D20D8",
  "ep_888D2F00",
  "ep_888D3468",
  "ep_888D3478",
  "ep_888D3560",
  "ep_888D3618",
  "ep_888D3638",
  "ep_888D36F0",
  "ep_888D3710",
  "ep_888D3718",
  "ep_888D3720",
  "ep_888D37D0",
  "ep_888D37D8",
  "ep_888D38F8",
  "ep_888D3A30",
  "ep_888D3AC8",
  "ep_888D3AF0",
  "ep_888D3B38",
  "ep_888D3B58",
  "ep_888D3FD8",
  "ep_888D4038",
  "ep_888D4070",
  "ep_888D4100",
  "ep_888D4190",
  "ep_888D4220",
  "ep_888D42B0",
  "ep_888D4320",
  "ep_888D4390",
  "ep_888D4400",
  "ep_888D4700",
  "ep_888D4740",
  "ep_888D4770",
  "ep_888D47A8",
  "ep_888D4820",
  "ep_888D4850",
  "ep_888D4888",
  "ep_888D48C0",
  "ep_888D49C0",
  "ep_888D49E0",
  "ep_888D4A80",
  "ep_888D4CA0",
  "ep_888D5798",
  "ep_888D57C8",
  "ep_888D5878",
  "ep_888D5978",
  "ep_888D5A20",
  "ep_888D5B20",
  "ep_888D5C18",
  "ep_888D5CC0",
  "ep_888D5D38",
  "ep_888D5DE0",
  "ep_888D5E80",
  "ep_888D5F00",
  "ep_888D62A0",
  "ep_888D6398",
  "ep_888D63E8",
  "ep_888D6508",
  "ep_888D6598",
  "ep_888D65E0",
  "ep_888D6620",
  "ep_888D66F0",
  "ep_888D67C0",
  "ep_888D6818",
  "ep_888D6C20",
  "ep_888D6C30",
  "ep_888D70B0",
  "ep_888D7388",
  "ep_888D7510",
  "ep_888D7680",
  "ep_888D79F0",
  "ep_888D7CE0",
  "ep_888D8198",
  "ep_888D8428",
  "ep_888D8720",
  "ep_888D8798",
  "ep_888D8800",
  "ep_888D88C8",
  "ep_888D88D8",
  "ep_888D8988",
  "ep_888D8998",
  "ep_888D8F68",
  "ep_888D9070",
  "ep_888D9838",
  "ep_888D98B8",
  "ep_888D9908",
  "ep_888D9950",
  "ep_888DAA58",
  "ep_888DAA78",
  "ep_888DAA98",
  "ep_888DAF90",
  "ep_888DB550",
  "ep_888DB628",
  "ep_888DB700",
  "ep_888DB760",
  "ep_888DB7C0",
  "ep_888DB810",
  "ep_888DB860",
  "ep_888DB8B0",
  "ep_888DB8E8",
  "ep_888DBAA8",
  "ep_888DBC78",
  "ep_888DBC90",
  "ep_888DBD80",
  "ep_888DBE00",
  "ep_888DBEE8",
  "ep_888DBF10",
  "ep_888DBF18",
  "ep_888DCC70",
  "ep_888DCC98",
  "ep_888DCCB0",
  "ep_888DCCC8",
  "ep_888DCCE0",
  "ep_888DCCF8",
  "ep_888DCD10",
  "ep_888DCD40",
  "ep_888DCD58",
  "ep_888DD008",
  "ep_888DD2F0",
  "ep_888DD348",
  "ep_888DD380",
  "ep_888DD470",
  "ep_888DD4B0",
  "ep_888DD5A8",
  "ep_888DE760",
  "ep_888DE7E0",
  "ep_888DF470",
  "ep_888E0070",
  "ep_888E0088",
  "ep_888E00A0",
  "ep_888E0710",
  "ep_888E0718",
  "ep_888E0720",
  "ep_888E0728",
  "ep_888E0740",
  "ep_888E0758",
  "ep_888E0770",
  "ep_888E0788",
  "ep_888E0790",
  "ep_888E0798",
  "ep_888E08F8",
  "ep_888E0910",
  "ep_888E0958",
  "ep_888E0A58",
  "ep_888E0B98",
  "ep_888E0BF0",
  "ep_888E0C30",
  "ep_888E0C40",
  "ep_888E0CD8",
  "ep_888E0DE8",
  "ep_888E1108",
  "ep_888E11E0",
  "ep_888E1540",
  "ep_888E15C0",
  "ep_888E1FD8",
  "ep_888E2148",
  "ep_888E23D0",
  "ep_888E3E88",
  "ep_888E3F70",
  "ep_888E3F80",
  "ep_888E4418",
  "ep_888E4460",
  "ep_888E4978",
  "ep_888E4A18",
  "ep_888E4E08",
  "ep_888E5AE8",
  "ep_888E5B48",
  "ep_888E6AE0",
  "ep_888E6B18",
  "ep_888E6C88",
  "ep_888E6D00",
  "ep_888E6D58",
  "ep_888E7948",
  "ep_888E79B0",
  "ep_888E79D0",
  "ep_888E7AD8",
  "ep_888E7CB8",
  "ep_888E7DD0",
  "ep_888E7F10",
  "ep_888E91F0",
  "ep_888E93A0",
  "ep_888E9468",
  "ep_888EAB38",
  "ep_888EABF8",
  "ep_888EAC80",
  "ep_888EB148",
  "ep_888EB150",
  "ep_888EB580",
  "Present",
  "ep_888EBBE8",
  "ep_888EC100",
  "ep_888EC2F8",
  "ep_888EC850",
  "ep_888ECC28",
  "ep_888EDA10",
  "ep_888F0CC0",
};
inline bool verbose() {
  if (g_always < 0) { const char* a = getenv("D3DTRACE_ALWAYS"); g_always = (a && *a && *a != '0') ? 1 : 0; }
  return g_always || g_verbose_frames > 0;
}
}  // namespace

extern "C" void __imp__sub_888D19C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D19C0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[0];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D19C0 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D19C0(ctx, base);
}

extern "C" void __imp__sub_888D1AF8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D1AF8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[1];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D1AF8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D1AF8(ctx, base);
}

extern "C" void __imp__sub_888D1B10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D1B10(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[2];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D1B10 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D1B10(ctx, base);
}

extern "C" void __imp__sub_888D1B28(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D1B28(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[3];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D1B28 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D1B28(ctx, base);
}

extern "C" void __imp__sub_888D1C48(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D1C48(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[4];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D1C48 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D1C48(ctx, base);
}

extern "C" void __imp__sub_888D20D8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D20D8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[5];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D20D8 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x r10=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D20D8(ctx, base);
}

extern "C" void __imp__sub_888D2F00(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D2F00(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[6];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D2F00 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x r10=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D2F00(ctx, base);
}

extern "C" void __imp__sub_888D3468(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3468(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[7];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3468 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3468(ctx, base);
}

extern "C" void __imp__sub_888D3478(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3478(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[8];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3478 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3478(ctx, base);
}

extern "C" void __imp__sub_888D3560(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3560(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[9];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3560 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3560(ctx, base);
}

extern "C" void __imp__sub_888D3618(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3618(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[10];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3618 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3618(ctx, base);
}

extern "C" void __imp__sub_888D3638(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3638(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[11];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3638 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3638(ctx, base);
}

extern "C" void __imp__sub_888D36F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D36F0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[12];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D36F0 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D36F0(ctx, base);
}

extern "C" void __imp__sub_888D3710(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3710(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[13];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3710 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3710(ctx, base);
}

extern "C" void __imp__sub_888D3718(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3718(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[14];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3718 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3718(ctx, base);
}

extern "C" void __imp__sub_888D3720(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3720(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[15];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3720 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3720(ctx, base);
}

extern "C" void __imp__sub_888D37D0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D37D0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[16];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D37D0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D37D0(ctx, base);
}

extern "C" void __imp__sub_888D37D8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D37D8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[17];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D37D8 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x r10=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D37D8(ctx, base);
}

extern "C" void __imp__sub_888D38F8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D38F8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[18];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D38F8 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D38F8(ctx, base);
}

extern "C" void __imp__sub_888D3A30(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3A30(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[19];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3A30 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3A30(ctx, base);
}

extern "C" void __imp__sub_888D3AC8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3AC8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[20];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3AC8 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3AC8(ctx, base);
}

extern "C" void __imp__sub_888D3AF0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3AF0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[21];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3AF0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3AF0(ctx, base);
}

extern "C" void __imp__sub_888D3B38(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3B38(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[22];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3B38 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3B38(ctx, base);
}

extern "C" void __imp__sub_888D3B58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3B58(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[23];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3B58 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3B58(ctx, base);
}

extern "C" void __imp__sub_888D3FD8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3FD8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[24];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D3FD8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D3FD8(ctx, base);
}

extern "C" void __imp__sub_888D4038(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4038(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[25];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4038 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4038(ctx, base);
}

extern "C" void __imp__sub_888D4070(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4070(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[26];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4070 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4070(ctx, base);
}

extern "C" void __imp__sub_888D4100(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4100(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[27];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4100 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4100(ctx, base);
}

extern "C" void __imp__sub_888D4190(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4190(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[28];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4190 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4190(ctx, base);
}

extern "C" void __imp__sub_888D4220(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4220(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[29];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4220 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4220(ctx, base);
}

extern "C" void __imp__sub_888D42B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D42B0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[30];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D42B0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D42B0(ctx, base);
}

extern "C" void __imp__sub_888D4320(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4320(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[31];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4320 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4320(ctx, base);
}

extern "C" void __imp__sub_888D4390(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4390(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[32];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4390 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4390(ctx, base);
}

extern "C" void __imp__sub_888D4400(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4400(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[33];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4400 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4400(ctx, base);
}

extern "C" void __imp__sub_888D4700(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4700(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[34];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4700 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4700(ctx, base);
}

extern "C" void __imp__sub_888D4740(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4740(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[35];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4740 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4740(ctx, base);
}

extern "C" void __imp__sub_888D4770(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4770(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[36];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4770 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4770(ctx, base);
}

extern "C" void __imp__sub_888D47A8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D47A8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[37];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D47A8 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D47A8(ctx, base);
}

extern "C" void __imp__sub_888D4820(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4820(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[38];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4820 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4820(ctx, base);
}

extern "C" void __imp__sub_888D4850(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4850(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[39];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4850 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4850(ctx, base);
}

extern "C" void __imp__sub_888D4888(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4888(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[40];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4888 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4888(ctx, base);
}

extern "C" void __imp__sub_888D48C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D48C0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[41];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D48C0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D48C0(ctx, base);
}

extern "C" void __imp__sub_888D49C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D49C0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[42];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D49C0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D49C0(ctx, base);
}

extern "C" void __imp__sub_888D49E0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D49E0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[43];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D49E0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D49E0(ctx, base);
}

extern "C" void __imp__sub_888D4A80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4A80(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[44];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4A80 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4A80(ctx, base);
}

extern "C" void __imp__sub_888D4CA0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4CA0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[45];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D4CA0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D4CA0(ctx, base);
}

extern "C" void __imp__sub_888D5798(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5798(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[46];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5798 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5798(ctx, base);
}

extern "C" void __imp__sub_888D57C8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D57C8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[47];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D57C8 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D57C8(ctx, base);
}

extern "C" void __imp__sub_888D5878(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5878(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[48];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5878 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5878(ctx, base);
}

extern "C" void __imp__sub_888D5978(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5978(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[49];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5978 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5978(ctx, base);
}

extern "C" void __imp__sub_888D5A20(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5A20(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[50];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5A20 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5A20(ctx, base);
}

extern "C" void __imp__sub_888D5B20(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5B20(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[51];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5B20 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5B20(ctx, base);
}

extern "C" void __imp__sub_888D5C18(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5C18(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[52];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5C18 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5C18(ctx, base);
}

extern "C" void __imp__sub_888D5CC0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5CC0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[53];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5CC0 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5CC0(ctx, base);
}

extern "C" void __imp__sub_888D5D38(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5D38(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[54];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5D38 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5D38(ctx, base);
}

extern "C" void __imp__sub_888D5DE0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5DE0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[55];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5DE0 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5DE0(ctx, base);
}

extern "C" void __imp__sub_888D5E80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5E80(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[56];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5E80 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5E80(ctx, base);
}

extern "C" void __imp__sub_888D5F00(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5F00(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[57];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D5F00 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D5F00(ctx, base);
}

extern "C" void __imp__sub_888D62A0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D62A0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[58];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D62A0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D62A0(ctx, base);
}

extern "C" void __imp__sub_888D6398(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6398(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[59];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D6398 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D6398(ctx, base);
}

extern "C" void __imp__sub_888D63E8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D63E8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[60];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D63E8 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D63E8(ctx, base);
}

extern "C" void __imp__sub_888D6508(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6508(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[61];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D6508 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D6508(ctx, base);
}

extern "C" void __imp__sub_888D6598(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6598(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[62];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D6598 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D6598(ctx, base);
}

extern "C" void __imp__sub_888D65E0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D65E0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[63];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D65E0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D65E0(ctx, base);
}

extern "C" void __imp__sub_888D6620(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6620(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[64];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D6620 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D6620(ctx, base);
}

extern "C" void __imp__sub_888D66F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D66F0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[65];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D66F0 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D66F0(ctx, base);
}

extern "C" void __imp__sub_888D67C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D67C0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[66];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D67C0 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D67C0(ctx, base);
}

extern "C" void __imp__sub_888D6818(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6818(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[67];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D6818 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D6818(ctx, base);
}

extern "C" void __imp__sub_888D6C20(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6C20(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[68];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D6C20 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D6C20(ctx, base);
}

extern "C" void __imp__sub_888D6C30(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6C30(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[69];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D6C30 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D6C30(ctx, base);
}

extern "C" void __imp__sub_888D70B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D70B0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[70];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D70B0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D70B0(ctx, base);
}

extern "C" void __imp__sub_888D7388(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D7388(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[71];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D7388 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D7388(ctx, base);
}

extern "C" void __imp__sub_888D7510(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D7510(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[72];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D7510 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D7510(ctx, base);
}

extern "C" void __imp__sub_888D7680(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D7680(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[73];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D7680 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D7680(ctx, base);
}

extern "C" void __imp__sub_888D79F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D79F0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[74];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D79F0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D79F0(ctx, base);
}

extern "C" void __imp__sub_888D7CE0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D7CE0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[75];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D7CE0 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x r10=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D7CE0(ctx, base);
}

extern "C" void __imp__sub_888D8198(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8198(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[76];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D8198 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D8198(ctx, base);
}

extern "C" void __imp__sub_888D8428(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8428(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[77];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D8428 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D8428(ctx, base);
}

extern "C" void __imp__sub_888D8720(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8720(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[78];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D8720 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D8720(ctx, base);
}

extern "C" void __imp__sub_888D8798(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8798(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[79];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D8798 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D8798(ctx, base);
}

extern "C" void __imp__sub_888D8800(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8800(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[80];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D8800 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D8800(ctx, base);
}

extern "C" void __imp__sub_888D88C8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D88C8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[81];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D88C8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D88C8(ctx, base);
}

extern "C" void __imp__sub_888D88D8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D88D8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[82];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D88D8 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D88D8(ctx, base);
}

extern "C" void __imp__sub_888D8988(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8988(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[83];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D8988 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D8988(ctx, base);
}

extern "C" void __imp__sub_888D8998(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8998(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[84];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D8998 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D8998(ctx, base);
}

extern "C" void __imp__sub_888D8F68(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8F68(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[85];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D8F68 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D8F68(ctx, base);
}

extern "C" void __imp__sub_888D9070(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D9070(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[86];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D9070 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D9070(ctx, base);
}

extern "C" void __imp__sub_888D9838(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D9838(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[87];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D9838 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D9838(ctx, base);
}

extern "C" void __imp__sub_888D98B8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D98B8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[88];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D98B8 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D98B8(ctx, base);
}

extern "C" void __imp__sub_888D9908(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D9908(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[89];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D9908 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D9908(ctx, base);
}

extern "C" void __imp__sub_888D9950(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D9950(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[90];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888D9950 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888D9950(ctx, base);
}

extern "C" void __imp__sub_888DAA58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DAA58(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[91];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DAA58 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DAA58(ctx, base);
}

extern "C" void __imp__sub_888DAA78(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DAA78(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[92];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DAA78 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DAA78(ctx, base);
}

extern "C" void __imp__sub_888DAA98(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DAA98(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[93];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DAA98 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DAA98(ctx, base);
}

extern "C" void __imp__sub_888DAF90(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DAF90(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[94];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DAF90 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x r10=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DAF90(ctx, base);
}

extern "C" void __imp__sub_888DB550(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB550(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[95];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DB550 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DB550(ctx, base);
}

extern "C" void __imp__sub_888DB628(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB628(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[96];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DB628 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DB628(ctx, base);
}

extern "C" void __imp__sub_888DB700(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB700(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[97];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DB700 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DB700(ctx, base);
}

extern "C" void __imp__sub_888DB760(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB760(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[98];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DB760 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DB760(ctx, base);
}

extern "C" void __imp__sub_888DB7C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB7C0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[99];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DB7C0 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DB7C0(ctx, base);
}

extern "C" void __imp__sub_888DB810(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB810(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[100];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DB810 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DB810(ctx, base);
}

extern "C" void __imp__sub_888DB860(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB860(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[101];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DB860 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DB860(ctx, base);
}

extern "C" void __imp__sub_888DB8B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB8B0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[102];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DB8B0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DB8B0(ctx, base);
}

extern "C" void __imp__sub_888DB8E8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB8E8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[103];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DB8E8 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DB8E8(ctx, base);
}

extern "C" void __imp__sub_888DBAA8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBAA8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[104];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DBAA8 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DBAA8(ctx, base);
}

extern "C" void __imp__sub_888DBC78(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBC78(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[105];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DBC78 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DBC78(ctx, base);
}

extern "C" void __imp__sub_888DBC90(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBC90(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[106];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DBC90 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DBC90(ctx, base);
}

extern "C" void __imp__sub_888DBD80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBD80(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[107];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DBD80 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DBD80(ctx, base);
}

extern "C" void __imp__sub_888DBE00(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBE00(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[108];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DBE00 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DBE00(ctx, base);
}

extern "C" void __imp__sub_888DBEE8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBEE8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[109];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DBEE8 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DBEE8(ctx, base);
}

extern "C" void __imp__sub_888DBF10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBF10(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[110];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DBF10 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DBF10(ctx, base);
}

extern "C" void __imp__sub_888DBF18(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBF18(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[111];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DBF18 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DBF18(ctx, base);
}

extern "C" void __imp__sub_888DCC70(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCC70(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[112];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DCC70 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DCC70(ctx, base);
}

extern "C" void __imp__sub_888DCC98(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCC98(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[113];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DCC98 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DCC98(ctx, base);
}

extern "C" void __imp__sub_888DCCB0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCCB0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[114];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DCCB0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DCCB0(ctx, base);
}

extern "C" void __imp__sub_888DCCC8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCCC8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[115];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DCCC8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DCCC8(ctx, base);
}

extern "C" void __imp__sub_888DCCE0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCCE0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[116];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DCCE0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DCCE0(ctx, base);
}

extern "C" void __imp__sub_888DCCF8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCCF8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[117];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DCCF8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DCCF8(ctx, base);
}

extern "C" void __imp__sub_888DCD10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCD10(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[118];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DCD10 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DCD10(ctx, base);
}

extern "C" void __imp__sub_888DCD40(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCD40(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[119];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DCD40 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DCD40(ctx, base);
}

extern "C" void __imp__sub_888DCD58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCD58(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[120];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DCD58 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DCD58(ctx, base);
}

extern "C" void __imp__sub_888DD008(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD008(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[121];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DD008 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DD008(ctx, base);
}

extern "C" void __imp__sub_888DD2F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD2F0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[122];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DD2F0 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DD2F0(ctx, base);
}

extern "C" void __imp__sub_888DD348(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD348(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[123];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DD348 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DD348(ctx, base);
}

extern "C" void __imp__sub_888DD380(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD380(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[124];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DD380 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DD380(ctx, base);
}

extern "C" void __imp__sub_888DD470(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD470(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[125];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DD470 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DD470(ctx, base);
}

extern "C" void __imp__sub_888DD4B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD4B0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[126];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DD4B0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DD4B0(ctx, base);
}

extern "C" void __imp__sub_888DD5A8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD5A8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[127];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DD5A8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DD5A8(ctx, base);
}

extern "C" void __imp__sub_888DE760(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DE760(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[128];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DE760 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DE760(ctx, base);
}

extern "C" void __imp__sub_888DE7E0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DE7E0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[129];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DE7E0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DE7E0(ctx, base);
}

extern "C" void __imp__sub_888DF470(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DF470(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[130];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888DF470 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888DF470(ctx, base);
}

extern "C" void __imp__sub_888E0070(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0070(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[131];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0070 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0070(ctx, base);
}

extern "C" void __imp__sub_888E0088(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0088(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[132];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0088 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0088(ctx, base);
}

extern "C" void __imp__sub_888E00A0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E00A0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[133];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E00A0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E00A0(ctx, base);
}

extern "C" void __imp__sub_888E0710(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0710(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[134];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0710 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0710(ctx, base);
}

extern "C" void __imp__sub_888E0718(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0718(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[135];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0718 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0718(ctx, base);
}

extern "C" void __imp__sub_888E0720(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0720(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[136];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0720 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0720(ctx, base);
}

extern "C" void __imp__sub_888E0728(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0728(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[137];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0728 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0728(ctx, base);
}

extern "C" void __imp__sub_888E0740(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0740(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[138];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0740 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0740(ctx, base);
}

extern "C" void __imp__sub_888E0758(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0758(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[139];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0758 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0758(ctx, base);
}

extern "C" void __imp__sub_888E0770(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0770(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[140];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0770 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0770(ctx, base);
}

extern "C" void __imp__sub_888E0788(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0788(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[141];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0788 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0788(ctx, base);
}

extern "C" void __imp__sub_888E0790(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0790(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[142];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0790 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0790(ctx, base);
}

extern "C" void __imp__sub_888E0798(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0798(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[143];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0798 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0798(ctx, base);
}

extern "C" void __imp__sub_888E08F8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E08F8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[144];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E08F8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E08F8(ctx, base);
}

extern "C" void __imp__sub_888E0910(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0910(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[145];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0910 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0910(ctx, base);
}

extern "C" void __imp__sub_888E0958(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0958(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[146];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0958 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0958(ctx, base);
}

extern "C" void __imp__sub_888E0A58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0A58(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[147];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0A58 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0A58(ctx, base);
}

extern "C" void __imp__sub_888E0B98(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0B98(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[148];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0B98 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0B98(ctx, base);
}

extern "C" void __imp__sub_888E0BF0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0BF0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[149];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0BF0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0BF0(ctx, base);
}

extern "C" void __imp__sub_888E0C30(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0C30(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[150];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0C30 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0C30(ctx, base);
}

extern "C" void __imp__sub_888E0C40(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0C40(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[151];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0C40 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0C40(ctx, base);
}

extern "C" void __imp__sub_888E0CD8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0CD8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[152];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0CD8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0CD8(ctx, base);
}

extern "C" void __imp__sub_888E0DE8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0DE8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[153];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E0DE8 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x r10=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E0DE8(ctx, base);
}

extern "C" void __imp__sub_888E1108(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E1108(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[154];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E1108 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E1108(ctx, base);
}

extern "C" void __imp__sub_888E11E0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E11E0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[155];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E11E0 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E11E0(ctx, base);
}

extern "C" void __imp__sub_888E1540(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E1540(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[156];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E1540 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E1540(ctx, base);
}

extern "C" void __imp__sub_888E15C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E15C0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[157];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E15C0 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E15C0(ctx, base);
}

extern "C" void __imp__sub_888E1FD8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E1FD8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[158];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E1FD8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E1FD8(ctx, base);
}

extern "C" void __imp__sub_888E2148(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E2148(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[159];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E2148 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E2148(ctx, base);
}

extern "C" void __imp__sub_888E23D0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E23D0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[160];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E23D0 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E23D0(ctx, base);
}

extern "C" void __imp__sub_888E3E88(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E3E88(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[161];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E3E88 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E3E88(ctx, base);
}

extern "C" void __imp__sub_888E3F70(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E3F70(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[162];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E3F70 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E3F70(ctx, base);
}

extern "C" void __imp__sub_888E3F80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E3F80(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[163];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E3F80 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E3F80(ctx, base);
}

extern "C" void __imp__sub_888E4418(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4418(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[164];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E4418 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E4418(ctx, base);
}

extern "C" void __imp__sub_888E4460(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4460(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[165];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E4460 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x r10=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E4460(ctx, base);
}

extern "C" void __imp__sub_888E4978(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4978(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[166];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E4978 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x r10=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E4978(ctx, base);
}

extern "C" void __imp__sub_888E4A18(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4A18(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[167];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E4A18 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E4A18(ctx, base);
}

extern "C" void __imp__sub_888E4E08(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4E08(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[168];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E4E08 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E4E08(ctx, base);
}

extern "C" void __imp__sub_888E5AE8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E5AE8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[169];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E5AE8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E5AE8(ctx, base);
}

extern "C" void __imp__sub_888E5B48(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E5B48(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[170];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E5B48 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E5B48(ctx, base);
}

extern "C" void __imp__sub_888E6AE0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6AE0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[171];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E6AE0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E6AE0(ctx, base);
}

extern "C" void __imp__sub_888E6B18(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6B18(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[172];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E6B18 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E6B18(ctx, base);
}

extern "C" void __imp__sub_888E6C88(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6C88(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[173];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E6C88 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E6C88(ctx, base);
}

extern "C" void __imp__sub_888E6D00(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6D00(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[174];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E6D00 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E6D00(ctx, base);
}

extern "C" void __imp__sub_888E6D58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6D58(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[175];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E6D58 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E6D58(ctx, base);
}

extern "C" void __imp__sub_888E7948(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7948(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[176];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E7948 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E7948(ctx, base);
}

extern "C" void __imp__sub_888E79B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E79B0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[177];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E79B0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E79B0(ctx, base);
}

extern "C" void __imp__sub_888E79D0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E79D0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[178];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E79D0 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E79D0(ctx, base);
}

extern "C" void __imp__sub_888E7AD8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7AD8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[179];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E7AD8 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E7AD8(ctx, base);
}

extern "C" void __imp__sub_888E7CB8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7CB8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[180];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E7CB8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E7CB8(ctx, base);
}

extern "C" void __imp__sub_888E7DD0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7DD0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[181];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E7DD0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E7DD0(ctx, base);
}

extern "C" void __imp__sub_888E7F10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7F10(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[182];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E7F10 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E7F10(ctx, base);
}

extern "C" void __imp__sub_888E91F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E91F0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[183];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E91F0 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E91F0(ctx, base);
}

extern "C" void __imp__sub_888E93A0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E93A0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[184];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E93A0 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E93A0(ctx, base);
}

extern "C" void __imp__sub_888E9468(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E9468(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[185];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888E9468 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888E9468(ctx, base);
}

extern "C" void __imp__sub_888EAB38(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EAB38(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[186];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EAB38 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EAB38(ctx, base);
}

extern "C" void __imp__sub_888EABF8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EABF8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[187];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EABF8 r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EABF8(ctx, base);
}

extern "C" void __imp__sub_888EAC80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EAC80(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[188];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EAC80 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EAC80(ctx, base);
}

extern "C" void __imp__sub_888EB148(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EB148(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[189];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EB148 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EB148(ctx, base);
}

extern "C" void __imp__sub_888EB150(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EB150(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[190];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EB150 r3=%08x r4=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EB150(ctx, base);
}

extern "C" void __imp__sub_888EB580(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EB580(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[191];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EB580 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EB580(ctx, base);
}

extern "C" void __imp__sub_888EB588(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EB588(PPCContext& __restrict ctx, uint8_t* base) {
  // Frame boundary: report counts for the frame that just ended, then advance.
  if (g_frame) {
    fprintf(stderr, "D3DCOUNT f=%u", g_frame);
    for (int k = 0; k < kNumHooks; ++k) fprintf(stderr, " %s=%u", g_names[k], g_counts[k]);
    fputc('\n', stderr);
  }
  for (int k = 0; k < kNumHooks; ++k) g_counts[k] = 0;
  ++g_frame;
  if (g_verbose_frames > 0) --g_verbose_frames;
  if (!g_trigger) { const char* t = getenv("D3DTRACE_TRIGGER"); g_trigger = t ? t : ""; }
  if (*g_trigger && access(g_trigger, F_OK) == 0) {
    unlink(g_trigger);
    const char* n = getenv("D3DTRACE_FRAMES"); g_verbose_frames = n ? atoi(n) : 1;
    fprintf(stderr, "D3DTRACE-TRIGGER f=%u frames=%d\n", g_frame, g_verbose_frames);
    const char* gt = getenv("D3DTRACE_GPU_TRIGGER");
    if (gt && *gt) { const char* lg = getenv("D3DTRACE_GPU_LAG"); g_gpu_trigger_at = g_frame + (lg ? atoi(lg) : 2); }
  }
  if (g_gpu_trigger_at && g_frame >= g_gpu_trigger_at) {
    g_gpu_trigger_at = 0;
    FILE* tf = fopen(getenv("D3DTRACE_GPU_TRIGGER"), "w"); if (tf) fclose(tf);
    fprintf(stderr, "D3DTRACE-GPUTRIGGER f=%u\n", g_frame);
  }
  ++g_counts[192];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=Present r3=%08x r4=%08x r5=%08x r6=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EB588(ctx, base);
}

extern "C" void __imp__sub_888EBBE8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EBBE8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[193];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EBBE8 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EBBE8(ctx, base);
}

extern "C" void __imp__sub_888EC100(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EC100(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[194];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EC100 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EC100(ctx, base);
}

extern "C" void __imp__sub_888EC2F8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EC2F8(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[195];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EC2F8 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EC2F8(ctx, base);
}

extern "C" void __imp__sub_888EC850(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EC850(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[196];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EC850 r3=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EC850(ctx, base);
}

extern "C" void __imp__sub_888ECC28(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888ECC28(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[197];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888ECC28 r3=%08x r4=%08x r5=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888ECC28(ctx, base);
}

extern "C" void __imp__sub_888EDA10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EDA10(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[198];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888EDA10 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x r8=%08x r9=%08x r10=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888EDA10(ctx, base);
}

extern "C" void __imp__sub_888F0CC0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888F0CC0(PPCContext& __restrict ctx, uint8_t* base) {
  ++g_counts[199];
  if (verbose()) {
    fprintf(stderr, "D3DTRACE f=%u lr=%08x fn=ep_888F0CC0 r3=%08x r4=%08x r5=%08x r6=%08x r7=%08x", g_frame, (uint32_t)ctx.lr, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32);
    fputc('\n', stderr);
  }
  __imp__sub_888F0CC0(ctx, base);
}

extern "C" void d3dtrace_flush() { fflush(stderr); }
