// Generated by tools/d3d/timehooks.py - do not edit.
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <ctime>
#include <unistd.h>
#include "splitsecond_funcs.h"

namespace {

enum { kNumHooks = 200 };

const char* const g_names[kNumHooks] = {
  "D3D_888D19C0@19C0",
  "D3D_Get_888D1AF8@1AF8",
  "D3D_Get_888D1B10@1B10",
  "D3D_888D1B28@1B28",
  "D3D_888D1C48@1C48",
  "D3D_Set_888D20D8@20D8",
  "D3D_888D2F00@2F00",
  "D3D_Get_888D3468@3468",
  "D3D_888D3478@3478",
  "D3DDevice_SetShaderConstantF@3560",
  "D3D_888D3618@3618",
  "D3DDevice_SetShaderConstantF@3638",
  "D3D_888D36F0@36F0",
  "D3D_Get_888D3710@3710",
  "D3D_Get_888D3718@3718",
  "D3DDevice_SetShaderConstantF@3720",
  "D3D_Get_888D37D0@37D0",
  "D3DDevice_SetState@37D8",
  "D3DDevice_SetState@38F8",
  "D3D_888D3A30@3A30",
  "D3D_888D3AC8@3AC8",
  "D3D_888D3AF0@3AF0",
  "D3D_888D3B38@3B38",
  "D3D_Set_888D3B58@3B58",
  "D3DDevice_SetState_off16@3FD8",
  "D3DDevice_SetState_off16@4038",
  "D3DDevice_SetState_off16@4070",
  "D3DDevice_SetState_off16@4100",
  "D3DDevice_SetState_off16@4190",
  "D3DDevice_SetState_off16@4220",
  "D3DDevice_SetState_off16@42B0",
  "D3DDevice_SetState_off16@4320",
  "D3DDevice_SetState_off16@4390",
  "D3DDevice_SetState_off16@4400",
  "D3DDevice_SetState_off16@4700",
  "D3DDevice_SetState_off16@4740",
  "D3DDevice_SetState_off16@4770",
  "D3DDevice_SetState_off16@47A8",
  "D3DDevice_SetState_off16@4820",
  "D3DDevice_SetState_off16@4850",
  "D3DDevice_SetState_off16@4888",
  "D3DDevice_SetState_off16@48C0",
  "D3DDevice_SetState_off16@49C0",
  "D3DDevice_SetState_off16@49E0",
  "D3D_Set_888D4A80@4A80",
  "D3D_Set_888D4CA0@4CA0",
  "D3DDevice_SetState_off16@5798",
  "D3DDevice_SetState_off16@57C8",
  "D3D_Set_888D5878@5878",
  "D3D_Set_888D5978@5978",
  "D3D_Set_888D5A20@5A20",
  "D3D_Set_888D5B20@5B20",
  "D3D_Set_888D5C18@5C18",
  "D3D_Set_888D5CC0@5CC0",
  "D3D_Set_888D5D38@5D38",
  "D3D_Set_888D5DE0@5DE0",
  "D3D_Set_888D5E80@5E80",
  "D3D_Set_888D5F00@5F00",
  "D3D_Set_888D62A0@62A0",
  "D3D_888D6398@6398",
  "D3DDevice_SetState_off0@63E8",
  "D3D_Set_888D6508@6508",
  "D3D_888D6598@6598",
  "D3D_888D65E0@65E0",
  "D3DDevice_SetState@6620",
  "D3DDevice_SetState@66F0",
  "D3DDevice_SetState_off16@67C0",
  "D3D_888D6818@6818",
  "D3D_Set_888D6C20@6C20",
  "D3D_888D6C30@6C30",
  "D3DDevice_SetState_off12632@70B0",
  "D3D_Get_888D7388@7388",
  "D3DDevice_Tiling@7510",
  "D3DDevice_InsertFence@7680",
  "D3DDevice_SetState_off12896@79F0",
  "D3D_Set_888D7CE0@7CE0",
  "D3DDevice_SetState_off0@8198",
  "D3D_888D8428@8428",
  "D3DResource_Release@8720",
  "D3D_888D8798@8798",
  "D3DDevice_SetState@8800",
  "D3D_Get_888D88C8@88C8",
  "D3D_888D88D8@88D8",
  "D3D_Get_888D8988@8988",
  "D3D_888D8998@8998",
  "D3DDevice_InsertFence@8F68",
  "D3DDevice_InsertFence@9070",
  "D3DResource_Release@9838",
  "D3D_888D98B8@98B8",
  "D3D_888D9908@9908",
  "D3D_888D9950@9950",
  "D3D_Set_888DAA58@AA58",
  "D3D_888DAA78@AA78",
  "D3D_Get_888DAA98@AA98",
  "D3D_Dispatch_888DAF90@AF90",
  "D3D_Set_888DB550@B550",
  "D3D_Set_888DB628@B628",
  "D3D_Set_888DB700@B700",
  "D3D_Set_888DB760@B760",
  "D3D_Set_888DB7C0@B7C0",
  "D3D_Set_888DB810@B810",
  "D3D_888DB860@B860",
  "D3D_Set_888DB8B0@B8B0",
  "D3DDevice_SetState_off0@B8E8",
  "D3DDevice_SetState_off0@BAA8",
  "D3DDevice_SetState_off16@BC78",
  "D3D_888DBC90@BC90",
  "D3D_888DBD80@BD80",
  "D3D_888DBE00@BE00",
  "D3D_888DBEE8@BEE8",
  "D3D_Get_888DBF10@BF10",
  "D3D_Get_888DBF18@BF18",
  "D3D_888DCC70@CC70",
  "D3D_Get_888DCC98@CC98",
  "D3D_Get_888DCCB0@CCB0",
  "D3D_Get_888DCCC8@CCC8",
  "D3D_Get_888DCCE0@CCE0",
  "D3D_Get_888DCCF8@CCF8",
  "D3D_888DCD10@CD10",
  "D3D_Get_888DCD40@CD40",
  "D3D_Get_888DCD58@CD58",
  "D3D_Get_888DD008@D008",
  "D3D_888DD2F0@D2F0",
  "D3D_888DD348@D348",
  "D3DDevice_SetState@D380",
  "D3D_888DD470@D470",
  "D3D_888DD4B0@D4B0",
  "D3DDevice_SetState@D5A8",
  "D3D_888DE760@E760",
  "D3D_Get_888DE7E0@E7E0",
  "D3DDevice_SetRegister@F470",
  "D3D_Get_888E0070@0070",
  "D3D_Get_888E0088@0088",
  "D3D_Get_888E00A0@00A0",
  "D3D_Get_888E0710@0710",
  "D3D_Get_888E0718@0718",
  "D3D_Get_888E0720@0720",
  "D3D_Get_888E0728@0728",
  "D3D_Get_888E0740@0740",
  "D3D_Get_888E0758@0758",
  "D3D_Get_888E0770@0770",
  "D3D_Get_888E0788@0788",
  "D3D_Get_888E0790@0790",
  "D3D_Get_888E0798@0798",
  "D3D_Get_888E08F8@08F8",
  "D3D_888E0910@0910",
  "D3D_Get_888E0958@0958",
  "D3D_888E0A58@0A58",
  "D3D_888E0B98@0B98",
  "D3D_888E0BF0@0BF0",
  "D3D_Set_888E0C30@0C30",
  "D3DDevice_InsertFence@0C40",
  "D3D_888E0CD8@0CD8",
  "D3D_888E0DE8@0DE8",
  "D3DDevice_SetState@1108",
  "D3DDevice_BlockUntilIdle@11E0",
  "D3D_Get_888E1540@1540",
  "D3D_888E15C0@15C0",
  "D3DDevice_SetState@1FD8",
  "D3DDevice_BlockUntilIdle@2148",
  "D3D_888E23D0@23D0",
  "D3D_888E3E88@3E88",
  "D3D_Set_888E3F70@3F70",
  "D3DDevice_DrawVertices@3F80",
  "D3D_888E4418@4418",
  "D3DDevice_DrawIndexedVerticesUP@4460",
  "D3D_888E4978@4978",
  "D3DDevice_DrawVertices@4A18",
  "D3DDevice_DrawIndexedVertices@4E08",
  "D3D_888E5AE8@5AE8",
  "D3D_888E5B48@5B48",
  "D3D_Set_888E6AE0@6AE0",
  "D3D_888E6B18@6B18",
  "D3D_888E6C88@6C88",
  "D3D_888E6D00@6D00",
  "D3DDevice_SetState_off4@6D58",
  "D3D_Set_888E7948@7948",
  "D3D_888E79B0@79B0",
  "D3D_Set_888E79D0@79D0",
  "D3DDevice_DrawIndexedVerticesUP@7AD8",
  "D3DResource_Release@7CB8",
  "D3DResource_Release@7DD0",
  "D3D_888E7F10@7F10",
  "D3DDevice_SetState_off0@91F0",
  "D3D_Set_888E93A0@93A0",
  "D3DDevice_InsertFence@9468",
  "D3D_888EAB38@AB38",
  "D3D_Set_888EABF8@ABF8",
  "D3DDevice_SetState_off4@AC80",
  "D3D_Set_888EB148@B148",
  "D3D_Set_888EB150@B150",
  "D3D_Get_888EB580@B580",
  "D3DDevice_SetState_off4@B588",
  "D3DDevice_SetState@BBE8",
  "D3D_888EC100@C100",
  "D3DDevice_BlockUntilIdle@C2F8",
  "D3DDevice_SetShaderConstantF@C850",
  "D3DDevice_Tiling@CC28",
  "D3DDevice_Tiling@DA10",
  "D3DResource_Release@0CC0",
};

// Per-thread accumulators: the band is called from several guest threads and
// only the presenting thread's frame is interesting.
struct Acc {
  uint64_t ns[kNumHooks];
  uint32_t calls[kNumHooks];
  uint64_t total_ns;
  uint32_t total_calls;
  uint64_t frame_start_ns;
  int depth;
};
thread_local Acc g_acc = {};
uint32_t g_frame = 0;
int g_top = -1;
int g_every = -1;

inline uint64_t now_ns() {
  timespec t;
  clock_gettime(CLOCK_MONOTONIC, &t);
  return uint64_t(t.tv_sec) * 1000000000ull + uint64_t(t.tv_nsec);
}

inline void enter(uint64_t& t0) { t0 = now_ns(); }

inline void leave(int index, uint64_t t0) {
  uint64_t d = now_ns() - t0;
  g_acc.ns[index] += d;
  g_acc.calls[index]++;
  g_acc.total_ns += d;
  g_acc.total_calls++;
}

void report() {
  if (g_top < 0) {
    const char* top = getenv("D3DTIME_TOP");
    g_top = top ? atoi(top) : 10;
    const char* every = getenv("D3DTIME_EVERY");
    g_every = every ? atoi(every) : 1;
    if (g_every < 1) g_every = 1;
  }
  uint64_t now = now_ns();
  uint64_t wall = g_acc.frame_start_ns ? now - g_acc.frame_start_ns : 0;
  g_acc.frame_start_ns = now;
  uint32_t frame = g_frame++;
  if (wall && (frame % (uint32_t)g_every) == 0) {
    fprintf(stderr, "D3DTIME f=%u tid=%d wall_ms=%.3f d3d_ms=%.3f calls=%u top:",
            frame, (int)gettid(), double(wall) / 1e6,
            double(g_acc.total_ns) / 1e6, g_acc.total_calls);
    for (int n = 0; n < g_top; ++n) {
      int best = -1;
      uint64_t best_ns = 0;
      for (int i = 0; i < kNumHooks; ++i) {
        if (g_acc.ns[i] > best_ns) { best_ns = g_acc.ns[i]; best = i; }
      }
      if (best < 0) break;
      fprintf(stderr, " %s=%.3f/%u", g_names[best], double(best_ns) / 1e6,
              g_acc.calls[best]);
      g_acc.ns[best] = 0;  // consumed; the whole accumulator is cleared below
    }
    fputc('\n', stderr);
  }
  for (int i = 0; i < kNumHooks; ++i) { g_acc.ns[i] = 0; g_acc.calls[i] = 0; }
  g_acc.total_ns = 0;
  g_acc.total_calls = 0;
}

}  // namespace

extern "C" void __imp__sub_888D19C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D19C0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D19C0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D19C0(ctx, base);
  leave(0, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D1AF8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D1AF8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D1AF8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D1AF8(ctx, base);
  leave(1, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D1B10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D1B10(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D1B10(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D1B10(ctx, base);
  leave(2, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D1B28(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D1B28(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D1B28(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D1B28(ctx, base);
  leave(3, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D1C48(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D1C48(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D1C48(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D1C48(ctx, base);
  leave(4, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D20D8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D20D8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D20D8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D20D8(ctx, base);
  leave(5, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D2F00(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D2F00(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D2F00(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D2F00(ctx, base);
  leave(6, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3468(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3468(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3468(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3468(ctx, base);
  leave(7, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3478(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3478(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3478(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3478(ctx, base);
  leave(8, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3560(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3560(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3560(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3560(ctx, base);
  leave(9, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3638(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3638(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3638(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3638(ctx, base);
  leave(11, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D36F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D36F0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D36F0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D36F0(ctx, base);
  leave(12, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3710(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3710(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3710(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3710(ctx, base);
  leave(13, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3718(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3718(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3718(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3718(ctx, base);
  leave(14, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3720(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3720(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3720(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3720(ctx, base);
  leave(15, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D37D0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D37D0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D37D0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D37D0(ctx, base);
  leave(16, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D37D8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D37D8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D37D8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D37D8(ctx, base);
  leave(17, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D38F8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D38F8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D38F8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D38F8(ctx, base);
  leave(18, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3A30(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3A30(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3A30(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3A30(ctx, base);
  leave(19, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3AC8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3AC8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3AC8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3AC8(ctx, base);
  leave(20, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3AF0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3AF0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3AF0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3AF0(ctx, base);
  leave(21, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3B38(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3B38(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3B38(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3B38(ctx, base);
  leave(22, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3B58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3B58(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3B58(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3B58(ctx, base);
  leave(23, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D3FD8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D3FD8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D3FD8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D3FD8(ctx, base);
  leave(24, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4038(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4038(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4038(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4038(ctx, base);
  leave(25, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4070(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4070(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4070(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4070(ctx, base);
  leave(26, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4100(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4100(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4100(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4100(ctx, base);
  leave(27, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4190(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4190(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4190(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4190(ctx, base);
  leave(28, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4220(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4220(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4220(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4220(ctx, base);
  leave(29, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D42B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D42B0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D42B0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D42B0(ctx, base);
  leave(30, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4320(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4320(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4320(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4320(ctx, base);
  leave(31, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4390(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4390(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4390(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4390(ctx, base);
  leave(32, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4400(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4400(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4400(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4400(ctx, base);
  leave(33, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4700(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4700(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4700(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4700(ctx, base);
  leave(34, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4740(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4740(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4740(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4740(ctx, base);
  leave(35, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4770(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4770(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4770(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4770(ctx, base);
  leave(36, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D47A8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D47A8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D47A8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D47A8(ctx, base);
  leave(37, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4820(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4820(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4820(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4820(ctx, base);
  leave(38, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4850(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4850(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4850(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4850(ctx, base);
  leave(39, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4888(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4888(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4888(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4888(ctx, base);
  leave(40, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D48C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D48C0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D48C0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D48C0(ctx, base);
  leave(41, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D49C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D49C0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D49C0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D49C0(ctx, base);
  leave(42, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D49E0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D49E0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D49E0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D49E0(ctx, base);
  leave(43, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4A80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4A80(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4A80(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4A80(ctx, base);
  leave(44, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D4CA0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D4CA0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D4CA0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D4CA0(ctx, base);
  leave(45, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5798(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5798(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5798(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5798(ctx, base);
  leave(46, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D57C8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D57C8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D57C8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D57C8(ctx, base);
  leave(47, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5878(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5878(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5878(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5878(ctx, base);
  leave(48, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5978(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5978(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5978(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5978(ctx, base);
  leave(49, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5A20(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5A20(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5A20(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5A20(ctx, base);
  leave(50, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5B20(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5B20(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5B20(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5B20(ctx, base);
  leave(51, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5C18(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5C18(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5C18(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5C18(ctx, base);
  leave(52, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5CC0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5CC0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5CC0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5CC0(ctx, base);
  leave(53, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5D38(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5D38(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5D38(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5D38(ctx, base);
  leave(54, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5DE0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5DE0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5DE0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5DE0(ctx, base);
  leave(55, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5E80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5E80(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5E80(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5E80(ctx, base);
  leave(56, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D5F00(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D5F00(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D5F00(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D5F00(ctx, base);
  leave(57, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D62A0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D62A0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D62A0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D62A0(ctx, base);
  leave(58, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D6398(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6398(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D6398(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D6398(ctx, base);
  leave(59, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D63E8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D63E8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D63E8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D63E8(ctx, base);
  leave(60, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D6508(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6508(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D6508(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D6508(ctx, base);
  leave(61, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D6598(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6598(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D6598(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D6598(ctx, base);
  leave(62, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D65E0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D65E0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D65E0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D65E0(ctx, base);
  leave(63, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D6620(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6620(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D6620(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D6620(ctx, base);
  leave(64, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D66F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D66F0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D66F0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D66F0(ctx, base);
  leave(65, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D67C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D67C0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D67C0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D67C0(ctx, base);
  leave(66, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D6818(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6818(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D6818(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D6818(ctx, base);
  leave(67, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D6C20(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6C20(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D6C20(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D6C20(ctx, base);
  leave(68, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D6C30(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D6C30(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D6C30(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D6C30(ctx, base);
  leave(69, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D70B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D70B0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D70B0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D70B0(ctx, base);
  leave(70, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D7388(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D7388(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D7388(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D7388(ctx, base);
  leave(71, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D7510(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D7510(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D7510(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D7510(ctx, base);
  leave(72, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D7680(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D7680(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D7680(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D7680(ctx, base);
  leave(73, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D79F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D79F0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D79F0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D79F0(ctx, base);
  leave(74, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D7CE0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D7CE0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D7CE0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D7CE0(ctx, base);
  leave(75, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D8198(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8198(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D8198(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D8198(ctx, base);
  leave(76, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D8428(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8428(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D8428(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D8428(ctx, base);
  leave(77, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D8720(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8720(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D8720(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D8720(ctx, base);
  leave(78, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D8798(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8798(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D8798(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D8798(ctx, base);
  leave(79, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D8800(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8800(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D8800(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D8800(ctx, base);
  leave(80, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D88C8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D88C8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D88C8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D88C8(ctx, base);
  leave(81, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D88D8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D88D8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D88D8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D88D8(ctx, base);
  leave(82, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D8988(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8988(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D8988(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D8988(ctx, base);
  leave(83, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D8998(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8998(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D8998(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D8998(ctx, base);
  leave(84, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D8F68(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D8F68(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D8F68(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D8F68(ctx, base);
  leave(85, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D9070(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D9070(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D9070(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D9070(ctx, base);
  leave(86, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D9838(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D9838(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D9838(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D9838(ctx, base);
  leave(87, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D98B8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D98B8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D98B8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D98B8(ctx, base);
  leave(88, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D9908(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D9908(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D9908(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D9908(ctx, base);
  leave(89, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888D9950(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888D9950(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888D9950(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888D9950(ctx, base);
  leave(90, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DAA58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DAA58(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DAA58(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DAA58(ctx, base);
  leave(91, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DAA78(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DAA78(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DAA78(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DAA78(ctx, base);
  leave(92, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DAA98(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DAA98(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DAA98(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DAA98(ctx, base);
  leave(93, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DAF90(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DAF90(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DAF90(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DAF90(ctx, base);
  leave(94, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DB550(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB550(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DB550(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DB550(ctx, base);
  leave(95, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DB628(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB628(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DB628(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DB628(ctx, base);
  leave(96, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DB700(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB700(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DB700(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DB700(ctx, base);
  leave(97, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DB760(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB760(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DB760(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DB760(ctx, base);
  leave(98, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DB7C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB7C0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DB7C0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DB7C0(ctx, base);
  leave(99, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DB810(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB810(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DB810(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DB810(ctx, base);
  leave(100, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DB860(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB860(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DB860(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DB860(ctx, base);
  leave(101, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DB8B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB8B0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DB8B0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DB8B0(ctx, base);
  leave(102, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DB8E8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DB8E8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DB8E8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DB8E8(ctx, base);
  leave(103, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DBAA8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBAA8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DBAA8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DBAA8(ctx, base);
  leave(104, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DBC78(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBC78(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DBC78(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DBC78(ctx, base);
  leave(105, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DBC90(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBC90(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DBC90(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DBC90(ctx, base);
  leave(106, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DBD80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBD80(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DBD80(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DBD80(ctx, base);
  leave(107, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DBE00(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBE00(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DBE00(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DBE00(ctx, base);
  leave(108, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DBEE8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBEE8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DBEE8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DBEE8(ctx, base);
  leave(109, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DBF10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBF10(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DBF10(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DBF10(ctx, base);
  leave(110, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DBF18(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DBF18(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DBF18(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DBF18(ctx, base);
  leave(111, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DCC70(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCC70(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DCC70(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DCC70(ctx, base);
  leave(112, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DCC98(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCC98(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DCC98(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DCC98(ctx, base);
  leave(113, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DCCB0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCCB0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DCCB0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DCCB0(ctx, base);
  leave(114, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DCCC8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCCC8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DCCC8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DCCC8(ctx, base);
  leave(115, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DCCE0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCCE0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DCCE0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DCCE0(ctx, base);
  leave(116, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DCCF8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCCF8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DCCF8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DCCF8(ctx, base);
  leave(117, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DCD10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCD10(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DCD10(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DCD10(ctx, base);
  leave(118, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DCD40(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCD40(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DCD40(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DCD40(ctx, base);
  leave(119, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DCD58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DCD58(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DCD58(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DCD58(ctx, base);
  leave(120, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DD008(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD008(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DD008(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DD008(ctx, base);
  leave(121, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DD2F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD2F0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DD2F0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DD2F0(ctx, base);
  leave(122, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DD348(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD348(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DD348(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DD348(ctx, base);
  leave(123, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DD380(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD380(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DD380(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DD380(ctx, base);
  leave(124, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DD470(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD470(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DD470(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DD470(ctx, base);
  leave(125, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DD4B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD4B0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DD4B0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DD4B0(ctx, base);
  leave(126, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DD5A8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DD5A8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DD5A8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DD5A8(ctx, base);
  leave(127, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DE760(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DE760(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DE760(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DE760(ctx, base);
  leave(128, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DE7E0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DE7E0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DE7E0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DE7E0(ctx, base);
  leave(129, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888DF470(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888DF470(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888DF470(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888DF470(ctx, base);
  leave(130, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0070(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0070(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0070(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0070(ctx, base);
  leave(131, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0088(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0088(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0088(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0088(ctx, base);
  leave(132, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E00A0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E00A0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E00A0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E00A0(ctx, base);
  leave(133, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0710(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0710(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0710(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0710(ctx, base);
  leave(134, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0718(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0718(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0718(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0718(ctx, base);
  leave(135, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0720(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0720(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0720(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0720(ctx, base);
  leave(136, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0728(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0728(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0728(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0728(ctx, base);
  leave(137, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0740(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0740(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0740(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0740(ctx, base);
  leave(138, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0758(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0758(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0758(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0758(ctx, base);
  leave(139, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0770(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0770(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0770(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0770(ctx, base);
  leave(140, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0788(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0788(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0788(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0788(ctx, base);
  leave(141, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0790(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0790(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0790(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0790(ctx, base);
  leave(142, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0798(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0798(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0798(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0798(ctx, base);
  leave(143, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E08F8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E08F8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E08F8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E08F8(ctx, base);
  leave(144, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0910(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0910(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0910(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0910(ctx, base);
  leave(145, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0958(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0958(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0958(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0958(ctx, base);
  leave(146, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0A58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0A58(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0A58(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0A58(ctx, base);
  leave(147, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0B98(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0B98(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0B98(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0B98(ctx, base);
  leave(148, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0BF0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0BF0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0BF0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0BF0(ctx, base);
  leave(149, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0C30(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0C30(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0C30(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0C30(ctx, base);
  leave(150, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0C40(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0C40(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0C40(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0C40(ctx, base);
  leave(151, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0CD8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0CD8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0CD8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0CD8(ctx, base);
  leave(152, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E0DE8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E0DE8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E0DE8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E0DE8(ctx, base);
  leave(153, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E1108(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E1108(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E1108(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E1108(ctx, base);
  leave(154, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E11E0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E11E0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E11E0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E11E0(ctx, base);
  leave(155, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E1540(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E1540(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E1540(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E1540(ctx, base);
  leave(156, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E15C0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E15C0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E15C0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E15C0(ctx, base);
  leave(157, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E1FD8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E1FD8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E1FD8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E1FD8(ctx, base);
  leave(158, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E2148(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E2148(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E2148(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E2148(ctx, base);
  leave(159, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E23D0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E23D0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E23D0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E23D0(ctx, base);
  leave(160, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E3E88(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E3E88(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E3E88(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E3E88(ctx, base);
  leave(161, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E3F70(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E3F70(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E3F70(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E3F70(ctx, base);
  leave(162, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E3F80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E3F80(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E3F80(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E3F80(ctx, base);
  leave(163, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E4418(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4418(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E4418(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E4418(ctx, base);
  leave(164, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E4460(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4460(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E4460(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E4460(ctx, base);
  leave(165, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E4978(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4978(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E4978(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E4978(ctx, base);
  leave(166, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E4A18(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4A18(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E4A18(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E4A18(ctx, base);
  leave(167, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E4E08(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E4E08(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E4E08(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E4E08(ctx, base);
  leave(168, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E5AE8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E5AE8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E5AE8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E5AE8(ctx, base);
  leave(169, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E5B48(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E5B48(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E5B48(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E5B48(ctx, base);
  leave(170, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E6AE0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6AE0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E6AE0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E6AE0(ctx, base);
  leave(171, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E6B18(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6B18(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E6B18(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E6B18(ctx, base);
  leave(172, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E6C88(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6C88(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E6C88(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E6C88(ctx, base);
  leave(173, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E6D00(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6D00(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E6D00(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E6D00(ctx, base);
  leave(174, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E6D58(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E6D58(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E6D58(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E6D58(ctx, base);
  leave(175, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E7948(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7948(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E7948(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E7948(ctx, base);
  leave(176, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E79B0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E79B0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E79B0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E79B0(ctx, base);
  leave(177, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E79D0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E79D0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E79D0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E79D0(ctx, base);
  leave(178, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E7AD8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7AD8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E7AD8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E7AD8(ctx, base);
  leave(179, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E7CB8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7CB8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E7CB8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E7CB8(ctx, base);
  leave(180, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E7DD0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7DD0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E7DD0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E7DD0(ctx, base);
  leave(181, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E7F10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E7F10(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E7F10(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E7F10(ctx, base);
  leave(182, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E91F0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E91F0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E91F0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E91F0(ctx, base);
  leave(183, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E93A0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E93A0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E93A0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E93A0(ctx, base);
  leave(184, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888E9468(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888E9468(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888E9468(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888E9468(ctx, base);
  leave(185, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EAB38(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EAB38(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EAB38(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EAB38(ctx, base);
  leave(186, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EABF8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EABF8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EABF8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EABF8(ctx, base);
  leave(187, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EAC80(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EAC80(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EAC80(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EAC80(ctx, base);
  leave(188, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EB148(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EB148(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EB148(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EB148(ctx, base);
  leave(189, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EB150(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EB150(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EB150(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EB150(ctx, base);
  leave(190, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EB580(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EB580(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EB580(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EB580(ctx, base);
  leave(191, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EB588(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EB588(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EB588(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EB588(ctx, base);
  leave(192, t0);
  --g_acc.depth;
  report();
}

extern "C" void __imp__sub_888EBBE8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EBBE8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EBBE8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EBBE8(ctx, base);
  leave(193, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EC100(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EC100(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EC100(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EC100(ctx, base);
  leave(194, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EC2F8(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EC2F8(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EC2F8(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EC2F8(ctx, base);
  leave(195, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EC850(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EC850(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EC850(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EC850(ctx, base);
  leave(196, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888ECC28(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888ECC28(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888ECC28(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888ECC28(ctx, base);
  leave(197, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888EDA10(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888EDA10(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888EDA10(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888EDA10(ctx, base);
  leave(198, t0);
  --g_acc.depth;
}

extern "C" void __imp__sub_888F0CC0(PPCContext& __restrict, uint8_t*);
extern "C" void sub_888F0CC0(PPCContext& __restrict ctx, uint8_t* base) {
  if (g_acc.depth++) {
    __imp__sub_888F0CC0(ctx, base);
    --g_acc.depth;
    return;
  }
  uint64_t t0;
  enter(t0);
  __imp__sub_888F0CC0(ctx, base);
  leave(199, t0);
  --g_acc.depth;
}

