#!/usr/bin/env python3
"""make_font.py - turn a BDF bitmap font into the header the system blade draws.

    python3 tools/make_font.py spleen-8x16.bdf > src/font8x16.inc

The runtime draws its own pages (achievements, local scores) with a bitmap font
compiled into it, so that a page costs one buffer-to-image copy and no font
library, no file to find at runtime and no fallback to worry about. This is the
step that produces that header, kept in the tree so the header is reproducible
rather than a blob nobody can regenerate.

The font shipped is Spleen 8x16 by Frederic Cambus, BSD-2-Clause:

    https://github.com/fcambus/spleen

Chosen because its terms are unambiguous - the licence is stated in the BDF's
own header and in an SPDX identifier, so the provenance travels with the data -
and because it is a bitmap font DESIGNED at this size rather than a rasterised
outline, which is what keeps the strokes even at one pixel per pixel.

Only ASCII 0x20..0x7E is emitted. That is every character an achievement name,
a leaderboard name or a score row uses, and 95 glyphs of 16 bytes is 1.5 KB -
the whole Unicode range would be 16 KB of mostly unreachable table.

The BDF must have a uniform 8x16 bounding box; a font with per-glyph boxes would
need offsets applied and this refuses rather than silently misplacing rows.
"""

import hashlib
import sys

FIRST = 0x20
LAST = 0x7E
WIDTH = 8
HEIGHT = 16


def parse_bdf(text):
    """Every glyph in the file, as {codepoint: [16 row bytes]}."""
    glyphs = {}
    code = None
    box = None
    rows = None
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("ENCODING "):
            code = int(line.split()[1])
        elif line.startswith("BBX "):
            box = tuple(int(part) for part in line.split()[1:5])
        elif line == "BITMAP":
            rows = []
        elif line == "ENDCHAR":
            if code is not None and rows is not None:
                glyphs[code] = (box, rows)
            code, box, rows = None, None, None
        elif rows is not None:
            rows.append(line)
    return glyphs


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: make_font.py <font.bdf>\n")
        return 2
    path = sys.argv[1]
    with open(path, "rb") as handle:
        raw = handle.read()
    digest = hashlib.sha256(raw).hexdigest()
    glyphs = parse_bdf(raw.decode("latin-1"))

    out = []
    for code in range(FIRST, LAST + 1):
        if code not in glyphs:
            sys.stderr.write("font has no glyph for 0x%02X\n" % code)
            return 1
        box, rows = glyphs[code]
        if box != (WIDTH, HEIGHT, 0, -4):
            sys.stderr.write(
                "glyph 0x%02X has box %r, not a uniform %dx%d cell\n"
                % (code, box, WIDTH, HEIGHT))
            return 1
        if len(rows) != HEIGHT:
            sys.stderr.write("glyph 0x%02X has %d rows, not %d\n"
                             % (code, len(rows), HEIGHT))
            return 1
        out.append((code, [int(row, 16) & 0xFF for row in rows]))

    print("// font8x16.inc - GENERATED by tools/make_font.py; do not edit.")
    print("//")
    print("// Spleen 8x16, ASCII 0x20..0x7E. One byte per row, sixteen rows a")
    print("// glyph, top row first, bit 7 the leftmost pixel. Indexed by")
    print("// codepoint minus 0x20, so a lookup is arithmetic rather than a")
    print("// search.")
    print("//")
    print("// Source: https://github.com/fcambus/spleen, spleen-8x16.bdf")
    print("// sha256 %s" % digest)
    print("//")
    print("// SPDX-License-Identifier: BSD-2-Clause")
    print("//")
    print("// Copyright (c) 2018-2026, Frederic Cambus")
    print("// All rights reserved.")
    print("//")
    print("// Redistribution and use in source and binary forms, with or")
    print("// without modification, are permitted provided that the following")
    print("// conditions are met:")
    print("//")
    print("//   * Redistributions of source code must retain the above")
    print("//     copyright notice, this list of conditions and the following")
    print("//     disclaimer.")
    print("//")
    print("//   * Redistributions in binary form must reproduce the above")
    print("//     copyright notice, this list of conditions and the following")
    print("//     disclaimer in the documentation and/or other materials")
    print("//     provided with the distribution.")
    print("//")
    print("// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND")
    print("// CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES,")
    print("// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF")
    print("// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE")
    print("// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR")
    print("// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,")
    print("// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT")
    print("// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF")
    print("// USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED")
    print("// AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT")
    print("// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN")
    print("// ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE")
    print("// POSSIBILITY OF SUCH DAMAGE.")
    print("// clang-format off")
    for code, rows in out:
        # Spelled out where the character itself would change what the line
        # means: a trailing backslash continues a // comment onto the next line
        # and swallows the glyph after it, which compiles to a font one glyph
        # short of the table it declares.
        names = {0x20: "space", 0x5C: "backslash"}
        name = names.get(code, chr(code))
        print("    " + ", ".join("0x%02X" % row for row in rows) +
              ",  // 0x%02X %s" % (code, name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
