#!/usr/bin/env python3
"""Bakes assets/xbox360_controller.png into src/pad_image.inc.

    python3 tools/make_pad_image.py

This is the first embedded IMAGE in the tree, so it sets the convention, and the
convention is the one tools/make_font.py already established for the 8x16 font:
a script turns an asset into a C array that is checked in, and the array is what
the build compiles. Nothing is read from disk at run time. A port has to be one
self-contained binary - it runs from a package with no data directory beside it,
and an asset loaded at run time is an asset that is missing on somebody else's
machine.

WHY IT IS NOT JUST A HEX DUMP OF THE PNG. Decoding a PNG needs an inflate, and
this runtime deliberately has no zlib - it hand-rolled AES and LZX rather than
take dependencies. Storing the pixels raw is the other extreme: 512x421 RGBA is
860 KB, which is a 5 MB source file. So the pixels are quantised to a palette
and run-length encoded, which needs about twenty lines to decode and comes out
around 150 KB.

The numbers behind the two choices, so nobody has to re-measure them:

  * NO DITHERING. Floyd-Steinberg looks better on a gradient and destroys the
    run lengths - it turns flat plastic into noise. Measured at 448 wide:
    136 KB dithered against 115 KB not, and the dithered one also looks worse
    once it is scaled up again, because the dither pattern scales with it.
  * 128 COLOURS. The subject is a black controller, so a small palette spends
    almost all of itself on shades of black and leaves the four coloured
    buttons washed out - which is exactly what 64 did, and those buttons are
    the part a player actually reads. 128 costs 12 KB more and brings them
    back. 255 costs another 9 KB and looks the same.

The alpha channel is reduced to one bit, because that is all the compositor
uses: canvas::blit skips a pixel with zero alpha and writes every other one
opaque. Index 0 is reserved for transparent.
"""

import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("this needs Pillow: pip install --user pillow")

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(HERE, "assets", "xbox360_controller.png")
TARGET = os.path.join(HERE, "src", "pad_image.inc")

# Wide enough that the pane never magnifies it more than about 1.3:1 on a
# 5120x1440 display, which is where a photograph starts to look soft.
WIDTH = 512
COLOURS = 128


def main():
    image = Image.open(SOURCE)
    # Crop to what is actually drawn. The source has a transparent margin, and
    # every pixel of it would be stored and then skipped.
    box = image.getchannel("A").getbbox()
    image = image.crop(box)
    height = round(image.height * WIDTH / image.width)
    image = image.resize((WIDTH, height), Image.LANCZOS)

    opaque = image.getchannel("A").point(lambda v: 255 if v >= 128 else 0)
    quantised = image.convert("RGB").quantize(
        colors=COLOURS, method=Image.MEDIANCUT, dither=Image.NONE)
    palette = quantised.getpalette()[: COLOURS * 3]
    indices = list(quantised.tobytes())
    alpha = list(opaque.tobytes())
    # Index 0 is transparent, so every real colour moves up by one.
    pixels = [0 if alpha[i] == 0 else indices[i] + 1 for i in range(len(indices))]

    runs = bytearray()
    at = 0
    while at < len(pixels):
        value = pixels[at]
        length = 1
        while (at + length < len(pixels) and pixels[at + length] == value
               and length < 255):
            length += 1
        runs.append(length)
        runs.append(value)
        at += length

    def rows(data, per_line, formatter):
        out = []
        for start in range(0, len(data), per_line):
            chunk = data[start:start + per_line]
            out.append("    " + " ".join(formatter(v) for v in chunk))
        return "\n".join(out)

    with open(TARGET, "w", encoding="utf-8") as out:
        out.write(
            "// Generated by tools/make_pad_image.py - do not edit.\n"
            "//\n"
            "// A photograph of an Xbox 360 controller, quantised to a palette\n"
            "// and run-length encoded. Public domain (Evan-Amos); see\n"
            "// assets/PROVENANCE.md for the licence and for the trademark\n"
            "// rule that governs how it may be drawn.\n"
            "//\n"
            "// Palette entry 0 is TRANSPARENT and is not in kPadPalette:\n"
            "// a run of index 0 is skipped, index N draws kPadPalette[N - 1].\n"
            "// The runs are (length, index) byte pairs in row-major order.\n")
        out.write(f"constexpr uint32_t kPadImageWidth = {WIDTH};\n")
        out.write(f"constexpr uint32_t kPadImageHeight = {height};\n")
        out.write(f"constexpr uint8_t kPadPalette[{COLOURS}][3] = {{\n")
        for i in range(COLOURS):
            r, g, b = palette[i * 3:i * 3 + 3]
            out.write(f"    {{0x{r:02X}, 0x{g:02X}, 0x{b:02X}}},\n")
        out.write("};\n")
        out.write(f"constexpr uint8_t kPadRuns[{len(runs)}] = {{\n")
        out.write(rows(runs, 24, lambda v: f"0x{v:02X},"))
        out.write("\n};\n")

    print(f"{SOURCE} -> {TARGET}")
    print(f"  {WIDTH}x{height}, {COLOURS} colours, {len(runs)} bytes of runs "
          f"({len(runs) / 1024:.0f} KB, against "
          f"{WIDTH * height * 4 / 1024:.0f} KB raw)")


if __name__ == "__main__":
    main()
